import jsPDF from "jspdf";
import type { AnalysisResult } from "@/types/analysis";
import { ROBOTO_REGULAR_BASE64, ROBOTO_BOLD_BASE64 } from "@/lib/pdf-fonts";

function registerFonts(doc: jsPDF) {
  doc.addFileToVFS("Roboto-Regular.ttf", ROBOTO_REGULAR_BASE64);
  doc.addFont("Roboto-Regular.ttf", "Roboto", "normal");

  doc.addFileToVFS("Roboto-Bold.ttf", ROBOTO_BOLD_BASE64);
  doc.addFont("Roboto-Bold.ttf", "Roboto", "bold");

  doc.setFont("Roboto", "normal");
}

const COLORS = {
  primary: [109, 40, 217] as const,
  primaryDark: [76, 29, 149] as const,
  primaryLight: [237, 233, 254] as const,
  text: [31, 41, 55] as const,
  muted: [107, 114, 128] as const,
  border: [229, 231, 235] as const,
  cardBg: [246, 244, 255] as const,
  white: [255, 255, 255] as const,
  success: [16, 185, 129] as const,
  warning: [245, 158, 11] as const,
  danger: [239, 68, 68] as const,
};

const PAGE = {
  width: 210,
  height: 297,
  marginX: 15,
  contentWidth: 180,
  headerHeight: 32,
  bottom: 22,
  contentTop: 44,
};

function setText(doc: jsPDF, color: readonly number[]) {
  doc.setTextColor(color[0], color[1], color[2]);
}

function setFill(doc: jsPDF, color: readonly number[]) {
  doc.setFillColor(color[0], color[1], color[2]);
}

function setDraw(doc: jsPDF, color: readonly number[]) {
  doc.setDrawColor(color[0], color[1], color[2]);
}

function drawHeader(doc: jsPDF) {
  setFill(doc, COLORS.primary);
  doc.rect(0, 0, PAGE.width, PAGE.headerHeight, "F");

  setFill(doc, COLORS.white);
  doc.roundedRect(PAGE.marginX, 8, 16, 16, 3, 3, "F");
  setText(doc, COLORS.primary);
  doc.setFont("Roboto", "bold");
  doc.setFontSize(11);
  doc.text("FC", PAGE.marginX + 8, 18, { align: "center" });

  setText(doc, COLORS.white);
  doc.setFont("Roboto", "bold");
  doc.setFontSize(18);
  doc.text("FirstClick", PAGE.marginX + 22, 16);

  doc.setFont("Roboto", "normal");
  doc.setFontSize(9);
  doc.text("AI Product Validation Report", PAGE.marginX + 22, 23);

  setText(doc, COLORS.text);
}

function drawFooters(doc: jsPDF) {
  const totalPages = doc.getNumberOfPages();
  const today = new Date().toLocaleDateString("tr-TR");

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    setDraw(doc, COLORS.border);
    doc.line(PAGE.marginX, PAGE.height - PAGE.bottom, PAGE.width - PAGE.marginX, PAGE.height - PAGE.bottom);

    doc.setFont("Roboto", "normal");
    doc.setFontSize(8.5);
    setText(doc, COLORS.muted);

    doc.text(`Generated: ${today}`, PAGE.marginX, PAGE.height - 14);
    doc.text("Generated by FirstClick AI", PAGE.width / 2, PAGE.height - 14, { align: "center" });
    doc.text(`Page ${i} / ${totalPages}`, PAGE.width - PAGE.marginX, PAGE.height - 14, { align: "right" });

    setText(doc, COLORS.text);
  }
}

function ensureSpace(doc: jsPDF, y: number, required: number): number {
  if (y + required > PAGE.height - PAGE.bottom - 6) {
    doc.addPage();
    drawHeader(doc);
    return PAGE.contentTop;
  }
  return y;
}

function sectionTitle(doc: jsPDF, title: string, y: number): number {
  y = ensureSpace(doc, y, 16);

  setFill(doc, COLORS.primary);
  doc.roundedRect(PAGE.marginX, y - 6, PAGE.contentWidth, 10, 2, 2, "F");

  setText(doc, COLORS.white);
  doc.setFont("Roboto", "bold");
  doc.setFontSize(13);
  doc.text(title, PAGE.marginX + 5, y + 1);

  setText(doc, COLORS.text);
  return y + 14;
}

function scoreBar(doc: jsPDF, label: string, value: number, y: number, invert = false): number {
  y = ensureSpace(doc, y, 12);

  doc.setFont("Roboto", "bold");
  doc.setFontSize(10.5);
  setText(doc, COLORS.text);
  doc.text(label, PAGE.marginX, y);

  const barX = PAGE.marginX + 55;
  const barWidth = 95;
  const barHeight = 5;

  setDraw(doc, COLORS.border);
  setFill(doc, COLORS.primaryLight);
  doc.roundedRect(barX, y - 4, barWidth, barHeight, 1.5, 1.5, "FD");

  const effective = invert ? 100 - value : value;
  const clamped = Math.max(0, Math.min(effective, 100));

  let fillColor: readonly number[] = COLORS.success;
  if (clamped < 40) fillColor = COLORS.danger;
  else if (clamped < 70) fillColor = COLORS.warning;

  setFill(doc, fillColor);
  if (clamped > 0) {
    doc.roundedRect(barX, y - 4, (barWidth * clamped) / 100, barHeight, 1.5, 1.5, "F");
  }

  doc.setFont("Roboto", "bold");
  doc.setFontSize(10);
  setText(doc, COLORS.text);
  doc.text(`${value}/100`, barX + barWidth + 6, y);

  return y + 11;
}

function bulletList(doc: jsPDF, items: string[], y: number, numbered = false): number {
  doc.setFont("Roboto", "normal");
  doc.setFontSize(10.5);

  items.forEach((item, i) => {
    const lines = doc.splitTextToSize(item, PAGE.contentWidth - 14);
    y = ensureSpace(doc, y, lines.length * 5.5 + 4);

    if (numbered) {
      setFill(doc, COLORS.primary);
      doc.circle(PAGE.marginX + 2.5, y - 1.5, 3, "F");
      setText(doc, COLORS.white);
      doc.setFont("Roboto", "bold");
      doc.setFontSize(7.5);
      doc.text(String(i + 1), PAGE.marginX + 2.5, y - 0.2, { align: "center" });
    } else {
      setFill(doc, COLORS.primary);
      doc.circle(PAGE.marginX + 1.5, y - 1.8, 1.1, "F");
    }

    doc.setFont("Roboto", "normal");
    doc.setFontSize(10.5);
    setText(doc, COLORS.text);
    doc.text(lines, PAGE.marginX + 8, y);

    y += lines.length * 5.5 + 4;
  });

  return y;
}

function paragraph(doc: jsPDF, text: string, y: number): number {
  const lines = doc.splitTextToSize(text, PAGE.contentWidth - 10);
  y = ensureSpace(doc, y, lines.length * 5.5 + 6);

  doc.setFont("Roboto", "normal");
  doc.setFontSize(10.5);
  setText(doc, COLORS.text);
  doc.text(lines, PAGE.marginX + 3, y);

  return y + lines.length * 5.5 + 6;
}

function likelihoodColor(likelihood: string): readonly number[] {
  if (likelihood === "Yüksek") return COLORS.success;
  if (likelihood === "Orta") return COLORS.warning;
  return COLORS.danger;
}

function personaCard(
  doc: jsPDF,
  persona: AnalysisResult["personas"][number],
  y: number
): number {
  const fields: Array<{ label: string; value: string }> = [
    { label: "İlk İzlenim", value: persona.firstImpression },
    { label: "Anladığı Şey", value: persona.understood },
    { label: "Kafasının Karıştığı Nokta", value: persona.confusion },
    { label: "Vazgeçme Sebebi", value: persona.dropOffReason },
    { label: "Geliştirme Önerisi", value: persona.suggestion },
  ];

  const wrapped = fields.map((f) => ({
    label: f.label,
    lines: doc.splitTextToSize(f.value, PAGE.contentWidth - 16) as string[],
  }));

  const headerHeight = 12;
  const fieldsHeight = wrapped.reduce((sum, f) => sum + f.lines.length * 5 + 7, 0);
  const cardHeight = headerHeight + fieldsHeight + 6;

  y = ensureSpace(doc, y, Math.min(cardHeight, PAGE.height - PAGE.contentTop - PAGE.bottom));

  const cardTop = y - 6;
  setFill(doc, COLORS.cardBg);
  setDraw(doc, COLORS.border);
  doc.roundedRect(PAGE.marginX, cardTop, PAGE.contentWidth, cardHeight, 3, 3, "FD");

  doc.setFont("Roboto", "bold");
  doc.setFontSize(12.5);
  setText(doc, COLORS.primaryDark);
  doc.text(persona.name, PAGE.marginX + 6, y + 1);

  const badgeColor = likelihoodColor(persona.likelihood);
  const badgeText = `Kullanma: ${persona.likelihood}`;
  doc.setFont("Roboto", "bold");
  doc.setFontSize(8.5);
  const badgeWidth = doc.getTextWidth(badgeText) + 8;
  const badgeX = PAGE.marginX + PAGE.contentWidth - badgeWidth - 4;
  setFill(doc, badgeColor);
  doc.roundedRect(badgeX, y - 5, badgeWidth, 7, 2, 2, "F");
  setText(doc, COLORS.white);
  doc.text(badgeText, badgeX + 4, y - 0.5);

  y += 10;

  wrapped.forEach((f) => {
    doc.setFont("Roboto", "bold");
    doc.setFontSize(8.5);
    setText(doc, COLORS.muted);
    doc.text(f.label.toUpperCase(), PAGE.marginX + 6, y);
    y += 4.5;

    doc.setFont("Roboto", "normal");
    doc.setFontSize(10);
    setText(doc, COLORS.text);
    doc.text(f.lines, PAGE.marginX + 6, y);
    y += f.lines.length * 5 + 2.5;
  });

  setText(doc, COLORS.text);
  return y + 6;
}

export function generatePDF(
  result: AnalysisResult,
  productName?: string,
  source?: "openai" | "mock"
) {
  const doc = new jsPDF("p", "mm", "a4");
  registerFonts(doc);

  drawHeader(doc);

  let y = PAGE.contentTop;

  doc.setFont("Roboto", "bold");
  doc.setFontSize(16);
  setText(doc, COLORS.text);
  doc.text(productName || "Unknown Product", PAGE.marginX, y);
  y += 8;

  const today = new Date().toLocaleDateString("tr-TR");
  doc.setFont("Roboto", "normal");
  doc.setFontSize(10.5);
  setText(doc, COLORS.muted);
  doc.text(`Tarih: ${today}`, PAGE.marginX, y);
  y += 6;
  doc.text(`Analiz Kaynağı: ${source === "openai" ? "OpenAI" : "Demo (Mock)"}`, PAGE.marginX, y);
  setText(doc, COLORS.text);
  y += 12;

  y = sectionTitle(doc, "FirstClick Skorları", y);
  y = scoreBar(doc, "Genel Skor", result.overallScore, y);
  y = scoreBar(doc, "Anlaşılabilirlik", result.clarityScore, y);
  y = scoreBar(doc, "Kullanma İsteği", result.adoptionScore, y);
  y = scoreBar(doc, "Onboarding Riski", result.onboardingRiskScore, y, true);
  y = scoreBar(doc, "Hedef Kitle Uyumu", result.targetFitScore, y);
  y += 4;

  y = sectionTitle(doc, "Persona Simülasyonları", y);
  result.personas.forEach((persona) => {
    y = personaCard(doc, persona, y);
  });

  y = sectionTitle(doc, "En Büyük Kör Noktalar", y);
  y = bulletList(doc, result.blindSpots, y);
  y += 4;

  y = sectionTitle(doc, "Vazgeçme Noktaları", y);
  y = bulletList(doc, result.dropOffPoints, y);
  y += 4;

  y = sectionTitle(doc, "Öncelikli Aksiyon Planı", y);
  y = bulletList(doc, result.actionPlan, y, true);
  y += 4;

  y = sectionTitle(doc, "Daha İyi Ürün Anlatımı Önerisi", y);
  y = paragraph(doc, result.improvedPitch, y);
  y += 2;

  y = sectionTitle(doc, "Jüri / Yatırımcı Soruları", y);
  y = bulletList(doc, result.toughQuestions, y, true);

  drawFooters(doc);

  const safeName = (productName || "FirstClick_Report").replace(/[^a-z0-9]+/gi, "_");
  doc.save(`${safeName}.pdf`);
}